import type { Metadata } from "next";
import { Didact_Gothic } from "next/font/google";
import "./globals.css";

const didact_Gothic = Didact_Gothic({
  variable: "--font-didact-gothic",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Antoine Bentini",
  description: "Generated by kaohiso",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${didact_Gothic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
